language: bash

env:
  global:
    - GIT_AUTHOR_EMAIL=kawai.arch.jk@gmail.com
    - GIT_AUTHOR_NAME=hakaiSAN
    - HUGO_VERSION=0.53
    - secure: "A5w2sznLMY37URNQvMOwCvPrQH3HVsebzbip0C9tQTPhAkMvJ5uFBr8yZEpyu4pat+rN7ijXsWihf6qeG6fTzcTjUe1qyoHV8fbRCVvj1Mg4fgY0kCbzRhWcmekSsbJLRuM1VFCC25pV3iNNUCZyfqI1GmcXcZdwGDrmskrjlKwQLtZOAnPDUrOBSKzEmRHe46ymy7/m4qwyyo8bv8UN/EwZdi4eXQfHLLXxNfPw27PR5hdNpOYNQBnYdgNNhvci+bXVfwGVsfkgdXterREWCVDbrjKWYdKd3gdrlYC0YZUfNJnvMSUs5TtSdOcrKDU5YGRqqU9oGDNoxGL6p8EDnoeKbJ0c5HbBCY5SHJeq6KEehbMEWofiWVAsNhV+yAr5hGEoq4pvCl3o9ABjbiaoPqqoSn0plk2SPxcDj2nZv+IGCWscLW45c2+15h1h4ZXfJaYD2FEEXe2aJBNtyIoqngWpfiVi5kJ5KYw0lRo+PGMoulYIQxne83cdNcQKOKcXMihrQygTesuqhxVKjsuUsIXKNxPVumadYgux2Z1IfNi2SEgOV8Mj9deFIF/HnHz36+deRtbUueOmgf3qzBb+4NUviqogD6KoS6O7IO8dbmLr47f3FJavDgQikJWdyt7jsFwF+fcqhznxdQv1f9lRXwK+iS8Lb10J0aHHEkcWdgA="
    - GIT_URL=https://${GITHUB_TOKEN}@github.com/hakaiSAN/hakaisan.github.io.git

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz

before_deploy:
  - git remote set-url origin ${GIT_URL}
  - git checkout development 
  - git fetch origin master:remotes/origin/master
  - git worktree add -B master public origin/master
  - ./hugo

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x scripts/deploy.sh && scripts/deploy.sh
  on:
    branch: development
